### PR TITLE
Update test-electrum workflow to container bitcoindevkit/electrs:0.3.0

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

This updates our test-electrum CI workflow to use bitcoind `v0.21.1` and electrs `v0.8.10`. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by RCasatta** [comment]
Are you sure is electrs `0.8.10`?

Sorry for asking for confirmation but I can't explain this output (should happen when you pass `--cookie` instead of `--cookie_file`):

```
args: ["-vvv", "--db-dir", "/tmp/.tmpV6ctdW", "--network", "regtest", "--cookie-file", "/tmp/.tmpWivx8G/regtest/.cookie", "--daemon-rpc-addr", "127.0.0.1:39279", "--jsonrpc-import", "--electrum-rpc-addr", "0.0.0.0:41973", "--monitoring-addr", "0.0.0.0:46691"]
WARNING: cookie option is deprecated and will be removed in the future!
```

And I've seen there was a fix https://github.com/romanz/electrs/commit/52ad2f0af000508d1ba5374e72d549cf5c965c15 for inverted cookie logic between `0.8.9` and `0.8.10`


Also, there is no `electrs --version`

**Comment by notmandatory** [comment]
I started up the container locally and then exec'd into it and it tried to start it locally and looks like electrs version is `server_banner: "Welcome to electrs 0.8.10 (Electrum Rust Server)!"`. I'll take a look at your electrs repo and see if I can figure out what's going on. This is how I found the version:
```
% docker run -d --rm -p 127.0.0.1:18443-18444:18443-18444/tcp -p 127.0.0.1:60401:60401/tcp --name electrs bitcoindevkit/electrs:0.3.0

% docker exec -it electrs bash

root@bca798d660bf:/# /root/electrs 
WARNING: cookie option is deprecated and will be removed in the future!

You most likely want to use cookie_file instead.
If you really don't want to use cookie_file for a good reason and knowing the consequences use the auth option
See authentication section in electrs usage documentation for more details.
https://github.com/romanz/electrs/blob/master/doc/usage.md#configuration-files-and-priorities
Config { log: StdErrLog { verbosity: Warn, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Auto }, network_type: Bitcoin, db_path: "./db/mainnet", daemon_dir: "/root/.bitcoin", blocks_dir: "/root/.bitcoin/blocks", daemon_rpc_addr: 127.0.0.1:8332, electrum_rpc_addr: 0.0.0.0:60401, monitoring_addr: 127.0.0.1:4224, jsonrpc_import: false, index_batch_size: 10, bulk_index_threads: 8, tx_cache_size: 10485760, txid_limit: 100, server_banner: "Welcome to electrs 0.8.10 (Electrum Rust Server)!", blocktxids_cache_size: 10485760 }

root@61a4e06346dd:/# ps -elf
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root           1       0  0  80   0 -  4509 wait   17:01 ?        00:00:00 /bin/bash /root/entrypoint.sh
5 S root           8       1 12  80   0 - 377996 hrtime 17:01 ?       00:00:01 /root/bitcoind -regtest -server -daemon -fallba
4 S root          36       1  0  80   0 - 254691 futex_ 17:01 ?       00:00:00 /root/electrs --network regtest -vvv --jsonrpc-
4 S root          68       0  0  80   0 -  4562 wait   17:01 pts/0    00:00:00 bash
0 R root          79      68  0  80   0 -  8607 -      17:01 pts/0    00:00:00 ps -elf

root@61a4e06346dd:/# /root/electrs --help
Usage: /root/electrs [ARGUMENTS...]

Arguments:
        --conf                        Load configuration from this file.
        --conf-dir                    Load configuration from files in this 
                                      directory.
        --db-dir                      Directory to store index database (default
                                      : ./db/)
        --daemon-dir                  Data directory of Bitcoind (default: ~/.
                                      bitcoin/)
        --blocks-dir                  Analogous to bitcoind's -blocksdir option,
                                      this specifies the directory containing 
                                      the raw blocks files (blk*.dat)
        --cookie-file                 JSONRPC authentication cookie file (
                                      default: ~/.bitcoin/.cookie)
        --network                     Select Bitcoin network type ('bitcoin', '
                                      testnet', 'regtest' or 'signet')
        --electrum-rpc-addr           Electrum server JSONRPC 'addr:port' to 
                                      listen on (default: '127.0.0.1:50001' for 
                                      mainnet, '127.0.0.1:60001' for testnet, '
                                      127.0.0.1:60401' for regtest and '
                                      127.0.0.1:60601' for signet)
        --daemon-rpc-addr             Bitcoin daemon JSONRPC 'addr:port' to 
                                      connect (default: 127.0.0.1:8332 for 
                                      mainnet, 127.0.0.1:18332 for testnet, 
                                      127.0.0.1:18443 for regtest and 127.0.0.1:
                                      18554 for signet)
        --monitoring-addr             Prometheus monitoring 'addr:port' to 
                                      listen on (default: 127.0.0.1:4224 for 
                                      mainnet, 127.0.0.1:14224 for testnet, 
                                      127.0.0.1:24224 for regtest and 127.0.0.1:
                                      34224 for regtest)
        --wait-duration-secs          Duration to wait between bitcoind polling
        --index-batch-size            Number of blocks to get in one JSONRPC 
                                      request from bitcoind
        --bulk-index-threads          Number of threads used for bulk indexing (
                                      default: use the # of CPUs)
        --tx-cache-size-mb            Total size of transactions to cache (MB)
        --blocktxids-cache-size-mb    Total size of block transactions IDs to 
                                      cache (in MB)
        --txid-limit                  Number of transactions to lookup before 
                                      returning an error, to prevent 'too 
                                      popular' addresses from causing the RPC 
                                      server to get stuck (0 - disable the limit
                                      )
        --server-banner               The banner to be shown in the Electrum 
                                      console
        -v, --verbose                 Increase logging verbosity
        --timestamp                   Prepend log lines with a timestamp
        --jsonrpc-import              Use JSONRPC instead of directly importing 
                                      blk*.dat files. Useful for remote full 
                                      node or low memory system

```

**Comment by notmandatory** [comment]
It could be that I reused a docker tag that I'd already pushed to docker hub. I'm going to push with a new tag and see if that fixes it (even though Docker may not be our long term CI strategy).

**Comment by notmandatory** [comment]
Closing this one in favor of #368

**Pull request closed without merging**
