### PR TITLE
Use `apply_update` instead of `determine_changeset` + `apply_changeset` around the code

### PR DESCRIPTION
**Pull request by LagginTimes**
This PR implements #1081

### CODE REVIEW

**Review by vladimirfomene — APPROVED** [review]
Review ACK 395a1f74d4e7ccee419184241a6b5773ecf5737d

**Review by evanlinjin — APPROVED** [review]
ACK 395a1f74d4e7ccee419184241a6b5773ecf5737d

**Comment by evanlinjin** [comment]
@LagginTimes can you sign your commits? Thanks

**Review by evanlinjin — APPROVED** [review]
ACK c753584379185b0bd19d130ca39e44c8a6a65e65

**Pull request merged**
