### PR TITLE
tx_builder: Relax generic constraints on TxBuilder

### LINKED ISSUE #1312: Relax generic requirements on TxBuilder
Currently all methods on TxBuilder have the same generic requirements. I'm not sure all methods actually need to have those. It would be nice if all methods that actually don't need any of the requirements would be callable without the requirements.

For example, to call `add_foreign_utxo`, from reading the code, no generic requirements are actually required, it just pushes an item into a vector. So if the requirements were dropped, this code would look a lot simpler:
```rust
	fn add_anchors<A, B, C>(b: &mut bdk::TxBuilder<A, B, C>, anchors: &[OutPoint])
	where 
		B: bdk::wallet::coin_selection::CoinSelectionAlgorithm,
		C: bdk::wallet::tx_builder::TxBuilderContext,
	{
		for utxo in anchors {
			let psbt_in = psbt::Input {
				witness_utxo: Some(fee::dust_anchor()),
				witness_script: Some(fee::op_true_script()),
				final_script_witness: Some(Witness::new()),
				..Default::default()
			};
			b.add_foreign_utxo(*utxo, psbt_in, 33);
		}
	}
```

### PR DESCRIPTION
**Pull request by stevenroose**
Closes https://github.com/bitcoindevkit/bdk/issues/1312

### CODE REVIEW

**Review by storopoli — COMMENTED** [review]
It would be nice to add some test cases for the functionality you are fixing (similar to the code in the linked issue).

**Comment by stevenroose** [comment]
I don't think it's needed here. With generic constraints: if it compiles, it works. The lower the better.

Is there something I can/should do about the canceled CI builds?

**Comment by LLFourn** [comment]
I agree there's no need for tests on this and its best to relax generic constraints as much as possible in rust. No idea what CI is doing. @notmandatory any ideas?

**Comment by danielabrozzoni** [comment]
To be fair I'm not sure why the CI is failing only in this PR, while others are passing (maybe it's just that other PRs aren't touching the bdk code, and the CI cache is ✨ caching ✨ it?)

Anyways, I opened https://github.com/bitcoindevkit/bdk/pull/1357 to fix, once that's merged, can you rebase please?

**Comment by stevenroose** [comment]
Rebased on top of #1357, so let's see if that fixes CI.

**Comment by notmandatory** [comment]
#1357 is merged and it looks like all tests are now passing.

**Review by danielabrozzoni — APPROVED** [review]
ACK 2efa299d0486e0b08376a062e86c6ca8e03916da

**Pull request merged**
