### PR TITLE
Fix wrong key origin path in public descriptor templates

### LINKED ISSUE #817: Public descriptor templates for xkeys have wrong key origin path
**Describe the bug**  

In the examples for Bip44Public, Bip49Public, and Bip84Public the descriptor templates have the wrong network in the key origin path when given testnet. The network part of the origin path is always set to bitcoin (0).

**To Reproduce**  

See: 

https://docs.rs/bdk/latest/bdk/descriptor/template/struct.Bip44Public.html#example
https://docs.rs/bdk/latest/bdk/descriptor/template/struct.Bip49Public.html#example
https://docs.rs/bdk/latest/bdk/descriptor/template/struct.Bip84Public.html#example

**Expected behavior**  

If testnet is selected in the template constructor then the network part of the origin keypath should be 1.

**Build environment**  
 - BDK tag/commit: v0.25.0 
 - OS+version: any
 - Rust/Cargo version: 1.60.0 
 - Rust/Cargo target: any

**Additional context**  

@thunderbiscuit and I noticed this when we were working on `bdk-ffi` bindings for descriptor templates (bitcoindevkit/bdk-ffi#260).

### PR DESCRIPTION
**Pull request by yukibtc**
### Description

Fixes #817 

#### All Submissions:

* [X] I've signed all my commits
* [X] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [X] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [X] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK 703ad895c56be67e82dcb0b2fc95e5fa96121a29

**Comment by notmandatory** [comment]
This will be ready to merge after #822 goes in.

**Comment by notmandatory** [comment]
Hi, please rebase this one to pick up the CI fix which is required to merge. Thanks!

**Comment by yukibtc** [comment]
> Hi, please rebase this one to pick up the CI fix which is required to merge. Thanks!

Rebased :)

**Pull request merged**
