### PR TITLE
Run code coverage on every PR

### PR DESCRIPTION
**Pull request by danielabrozzoni**
#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Review by afilini — APPROVED** [review]
ACK 49a20dfd5e510d325207459cb924978e5c50d2a6

Waiting for the CI to finish before merging this

**Comment by danielabrozzoni** [comment]
I had to re-push to trigger the CI, but it should be good now 👍🏻

**Review by notmandatory — APPROVED** [review]
ACK aa0ea6aeff474a9934d4e9eb6e14ea1667573fc5

verified PR branch code coverage runs can be found here: https://coveralls.io/github/bitcoindevkit/bdk

**Review by afilini — APPROVED** [review]
ACK aa0ea6aeff474a9934d4e9eb6e14ea1667573fc5

**Pull request merged**
