### PR TITLE
Additional comments for `TransactionDetails`.

### PR DESCRIPTION
**Pull request by evanlinjin**
### Description

I'm not sure if this is needed or helpful, but this PR adds comments to describe how the `sent` and `received` fields of `TransactionDetails` are calculated.

I wasn't sure how it was done until I looked deeper into the codebase (but maybe I am too much of a beginner and this is common sense for most).

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
This is useful info. I think you need to rebase your branch to fix the CI test.

**Comment by evanlinjin** [comment]
> This is useful info. I think you need to rebase your branch to fix the CI test.

Thank you for the reply! Which branch should I rebase from? It seems I am up to date with `origin:master`.

P.S. I noticed that a dependency requires toolchain to be at least version `1.56.1`, so I have tried updating `cont_integration.yml` to reflect that.

P.S. It seems it is a required check that version `1.56.0` is tested against, but this is impossible with the dependency requiring `1.56.1`.

**Comment by thunderbiscuit** [comment]
+1 I like the additional comment. I also had questions around this a while back when I first looked at building UI around transactions; I was looking for a field that gave me the amount "sent" by my payment to the recipient(s), but that's not what the `sent` field is for in this case, and it's good to note it explicitly.

ACK [428c22d](https://github.com/bitcoindevkit/bdk/pull/633/commits/428c22dbbf2f5ca3da5620d7540f9180394dd7a7).

**Comment by danielabrozzoni** [comment]
Concept ACK!
Just one small thing, when we bump the MSRV we should also update the changelog and the readme. I did so in #638 (I didn't notice your PR before, sorry!). You can either update your commit to include the changelog/readme changes, or just rebase on top of mine. 

I honestly don't care if it's your or my PR that gets merged, I just want the CI fixed 😂

**Comment by evanlinjin** [comment]
> Concept ACK! Just one small thing, when we bump the MSRV we should also update the changelog and the readme. I did so in #638 (I didn't notice your PR before, sorry!). You can either update your commit to include the changelog/readme changes, or just rebase on top of mine.
> 
> I honestly don't care if it's your or my PR that gets merged, I just want the CI fixed joy

I rebased to save time haha. All done :)

**Comment by danielabrozzoni** [comment]
ACK 58b174bce3cb50bc77bcd6489e59a69dec7fbd26

**Comment by danielabrozzoni** [comment]
Sorry to bother you again with this, can you rebase on master? #638 has been merged, but I had to slightly modify it (I dropped the rustfmt commit as it's not needed anymore)

**Comment by evanlinjin** [comment]
> Sorry to bother you again with this, can you rebase on master? #638 has been merged, but I had to slightly modify it (I dropped the rustfmt commit as it's not needed anymore)

Not bothered at all. All done!

**Comment by danielabrozzoni** [comment]
You should also drop 7fb7718aaa175f444a4068082a507c49903ad757 and remove from 91026e4311d4c1d6585f20de11bba6f6b79492c1 the rustfmt changes :)

**Comment by evanlinjin** [comment]
> You should also drop [7fb7718](https://github.com/bitcoindevkit/bdk/commit/7fb7718aaa175f444a4068082a507c49903ad757) and remove from [91026e4](https://github.com/bitcoindevkit/bdk/commit/91026e4311d4c1d6585f20de11bba6f6b79492c1) the rustfmt changes :)

This is a lot of work for two lines of comments (just kidding haha). I think it's all done...

**Comment by danielabrozzoni** [comment]
re-ACK 77c7d0aae944dbd5a44ca9b8f239db0c9edcd4f8

**Review by afilini — APPROVED** [review]

**Pull request merged**
