### PR TITLE
Derive `Clone` on `AddressInfo`

### PR DESCRIPTION
**Pull request by praveenperera**
### Description

Derive `Clone` on `AddressInfo` so I can clone it

#### All Submissions:

* [X] I've signed all my commits
* [X] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [X] I ran `cargo fmt` and `cargo clippy` before committing

### Changelog notice

* Added `Clone` impl for `AddessInfo`

### CODE REVIEW

**Review by evanlinjin — COMMENTED** [review]
ConceptACK

Just two things before I ACK:

Can you please change the commit message to be of the [Conventional Commits](https://www.conventionalcommits.org/en/) format? I.e. `feat(wallet): Derive Clone on AddressInfo`.

Also, please include the **Changelog notice** section in the PR description. I.e.

```markdown
### Changelog notice

* Added `Clone` impl for `AddessInfo`.
```

Thanks in advance!

**Comment by praveenperera** [comment]
@evanlinjin sorry about that, complete

**Review by oleonardolima — APPROVED** [review]
ACK b84292787f3b7291b79a1a096a9fc6e5ba33045c

**Review by evanlinjin — APPROVED** [review]
ACK b84292787f3b7291b79a1a096a9fc6e5ba33045c

**Review by notmandatory — APPROVED** [review]
ACK b84292787f3b7291b79a1a096a9fc6e5ba33045c

**Pull request merged**
