### PR TITLE
Fix clippy warnings and enable clippy check in CI workflow

### LINKED ISSUE #118: Fix clippy warnings and enable the clippy CI job
To find [clippy](https://github.com/rust-lang/rust-clippy) warnings that need to be fixed (or selectively disabled) run: `cargo clippy -- -D warnings`

To enable the clippy CI job un-comment the `clippy` job in `.github/workflows/cont_integration.yml` 

Depends on https://github.com/bitcoindevkit/bdk/pull/117

### PR DESCRIPTION
**Pull request by notmandatory**
In this PR I fixed all the clippy warnings and enable the clippy check in the github actions CI workflow. I also simplified the workflow by using a new docker image built from the https://github.com/bitcoindevkit/bitcoin-regtest-box repo. 

Because of the clippy suggested code changes this PR is more than just a CI change and needs some review.

Improvements

- clippy checks performed and passing for rust versions 1.45.0 and stable (1.47.0) 
- `test-electrum` integration tests now executed from new docker image `bitcoinddevkit/electrs`
- continuous integration test time reduced from ~15 mins to ~9 mins

closes https://github.com/bitcoindevkit/bdk/issues/118

### CODE REVIEW

**Comment by jrawsthorne** [comment]
All the clippy changes look correct. Haven't looked at the ci changes because I don't know much about the infrastructure

**Comment by notmandatory** [comment]
@jrawsthorne thanks for checking the clippy changes. 

@afilini is it OK if I merge this ? or do you want to take a look and/or finish #115 first?

**Comment by afilini** [comment]
I see that the travis check is failing, how about we disable it entirely? I guess you could do it in this PR too since you are already touching some CI stuff.

**Review by afilini — APPROVED** [review]
Looks really good to me, I think you can merge it and then we'll think about #115 and #123

**Pull request merged**
