### PR TITLE
Update codecov@v2

### LINKED ISSUE #447: Upgrade Github Actions workflow to use codecov-action@v2
The current Github Actions [`codecov-action@v1` tool is being deprecated](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) and we must upgrade our `code_coverage.yml` workflow to the new version [`codecov-action@v2`](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) by early next year.

### PR DESCRIPTION
**Pull request by rajarshimaitra**
### Description

Fixes #447.  

### Notes to the reviewers

Some checks are failing on current master.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by rajarshimaitra** [comment]
rust version 1.46.0 is failing build test is failing, even in current master.

**Comment by notmandatory** [comment]
I think it's time to update our MSRV, what are your thoughts for #457?  This should fix the build issues we've been getting lately.

**Comment by afilini** [comment]
Try rebasing on #454 first, that should fix the CI

**Comment by rajarshimaitra** [comment]
Rebased on #457, CI passing now.

**Comment by notmandatory** [comment]
> Rebased on #457, CI passing now.

Sorry this should be rebased on `master` which now includes #454, without including 36fe4f42e651153fb28c1ee966aaf91b40961cad.  We need to discuss #457 and MSRV changes in our next team chat.

**Comment by rajarshimaitra** [comment]
Thanks. Rebased on master.

**Comment by notmandatory** [comment]
Now you just need to do a `git rebase -i HEAD~2` and `drop` commit d4304206419e2f2d5f7b5e45c756b537699be657.

**Comment by rajarshimaitra** [comment]
Ok, Does this look correct?

**Review by notmandatory — APPROVED** [review]
ACK 3b2b559910903f6edef2905ccfaa66d78b95c0dc

**Pull request merged**
