### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by tcharding**
### Description

While familiarizing myself with the project I did a few minor documentation improvements. 

- Patch 1 is a grammar fix
- Patch 2 is whitespace, I've tried to work out the project style, please feel free to correct me if I've misunderstood.
- Patch 3 is super trivial, add a couple of full stops.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
~* [ ] I ran `cargo fmt` and `cargo clippy` before committing~ Documentation only, no rust files touched.

### CODE REVIEW

**Comment by tcharding** [comment]
I'm not sure why CI is failing, this PR only touches markdown files?

**Comment by notmandatory** [comment]
> I'm not sure why CI is failing, this PR only touches markdown files?

Our CI always tests against the current `stable` rust version and it looks like you're the lucky winner of the first PR since the [rust stable version changed from 1.48.0 to 1.49.0](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html).  Apparently `1.49.0` includes [a new clippy warning](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-149), it's just a one line fix needed so can you add it in this PR?

```
error: manual `!RangeInclusive::contains` implementation
   --> src/blockchain/mod.rs:172:12
    |
172 |         if progress < 0.0 || progress > 100.0 {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `!(0.0..=100.0).contains(&progress)`
    |
    = note: `-D clippy::manual-range-contains` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
```

**Comment by tcharding** [comment]
> > I'm not sure why CI is failing, this PR only touches markdown files?
> 
> Our CI always tests against the current `stable` rust version and it looks like you're the lucky winner of the first PR since the [rust stable version changed from 1.48.0 to 1.49.0](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html). Apparently `1.49.0` includes [a new clippy warning](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-149), it's just a one line fix needed so can you add it in this PR?
> 
> ```
> error: manual `!RangeInclusive::contains` implementation
>    --> src/blockchain/mod.rs:172:12
>     |
> 172 |         if progress < 0.0 || progress > 100.0 {
>     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `!(0.0..=100.0).contains(&progress)`
>     |
>     = note: `-D clippy::manual-range-contains` implied by `-D warnings`
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
> ```

Awesome, thanks. Done.

**Comment by notmandatory** [comment]
Thanks, looks good!

ACK 04030bc

**Comment by notmandatory** [comment]
Sorry about the force push, but I needed a rebase to avoid a merge commit. Also cherry-picked your clippy fix into the `release/0.3.0` branch.

**Comment by tcharding** [comment]
> Sorry about the force push, but I needed a rebase to avoid a merge commit. Also cherry-picked your clippy fix into the `release/0.3.0` branch.

No sweat, thanks for doing so.

**Pull request merged**
