### PR TITLE
Use Esplora's `get_block_hash()` method

### PR DESCRIPTION
**Pull request by tnull**
### Description
This PR makes use of the recently added `get_block_hash()` API method of the Esplora client. 

Previously, we retrieved the entire header to extract the `BlockHash`. Funnily enough, the header was internally retrieved through a combination of getting hash by height and then getting the header by hash.

### Notes to the reviewers

This is currently blocked on the next release of `rust-esplora-client`.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by rajarshimaitra** [comment]
Seems like this needs a new release of `esplora-client`?

**Comment by tnull** [comment]
> This is currently blocked on the next release of `rust-esplora-client`.

Correct, as noted in the description. Feel free to add a corresponding tag.

**Comment by notmandatory** [comment]
The new esplora-client 0.2 was released today and will get updated in the upcoming bdk 0.24.0 milestone via #770. Since this PR doesn't look like an urgent change I added it to the 0.25.0 bdk milestone.

**Comment by tnull** [comment]
> The new esplora-client 0.2 was released today and will get updated in the upcoming bdk 0.24.0 milestone via #770. Since this PR doesn't look like an urgent change I added it to the 0.25.0 bdk milestone.

Fine with both, really no urgency from my side. That said, I'll rebase as soon as #770 lands.

**Comment by afilini** [comment]
Sorry I missed this PR and did the same change in #770 (your deprecation notice was very helpful!).

I'm going to close this one since it won't be needed anymore, sorry for not noticing it before.

**Pull request closed without merging**
