### PR TITLE
Bump bdk version to 1.0.0-alpha.11

### LINKED ISSUE #1435: Release 1.0.0-alpha.11
### Summary

This incremental bi-weekly release includes three big improvements. New electrum full_scan and sync APIs were added for more efficiently querying blockchain data. And the keychain::Changeset now includes public key descriptors and keychain::Balance uses bitcoin::Amount instead of u32 sats amounts. See the changelog for all the details. 

### Commit

TBD

### Changelog

Changed

- Include the descriptor in keychain::Changeset #1203 
- Update bdk_electrum crate to use sync/full-scan structs #1403 
- Update keychain::Balance to use bitcoin::Amount #1411  
- Change `bdk_testenv` to re-export internally used crates. #1414
- Updated documentation for `full_scan` and `sync` in `bdk_esplora`. #1427
  
### Checklist

Release numbering must follow [Semantic Versioning]. These steps assume the current `master` branch **development** version is *1.0.0-alpha.11*.

#### On the day of the feature freeze

Change the `master` branch to the 1.0.0-alpha.11 version:

- [x] Switch to the `master` branch.
- [x] Create a new PR branch called `bump_dev_1.0.0_alpha.11`.
- [x] Bump the `bump_dev_1.0.0_alpha.11` branch to the next development MINOR+1 version.
  - Bump the modified crates versions in their `Cargo.toml` files. [update this list with only changed crates]
    - [x] bdk
    - [x] bdk_chain
    - [x] bdk_bitcoind_rpc
    - [x] bdk_electrum
    - [x] bdk_esplora
    - [x] bdk_file_store
    - [x] bdk_testenv
    - [x] bdk_persist
  - The commit message should be: [update this list with only changed crates]
     ```
     Bump bdk version to 1.0.0-alpha.11
     
     bdk_chain to 0.14.0
     bdk_bitcoind_rpc to 0.10.0
     bdk_electrum to 0.13.0
     bdk_esplora to 0.13.0
     bdk_file_store to 0.11.0
     bdk_testenv to 0.4.0
     bdk_persist to 0.2.0
     ```
- [x] Create PR and merge the `bump_dev_1.0.0-alpha.11` branch to `master`. 
  - Title PR "Bump bdk version to 1.0.0-alpha.11".

#### On the day of the release

Tag and publish new release:

- [x] Add a tag to the `HEAD` commit in the `master` branch.
  - The tag name should be `v1.0.0-alpha.11`
  - The first line of the tag message should be "Release 1.0.0-alpha.11".
  - In the body of the tag message put a copy of the **Summary** and **Changelog** for the release.
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Wait for the CI to finish one last time.
- [x] Push the new tag to the `bitcoindevkit/bdk` repo.
- [x] Publish **all** the updated crates to crates.io. [update this list with only changed crates]
    - [x] bdk_chain
    - [x] bdk_testenv 
    - [x] bdk_bitcoind_rpc
    - [x] bdk_electrum
    - [x] bdk_esplora
    - [x] bdk_persist
    - [x] bdk_file_store
    - [x] bdk
- [x] Create the release on GitHub.
  - Go to "tags", click on the dots on the right and select "Create Release".
  - Set the title to `Release 1.0.0-alpha.11`.
  - In the release notes body put the **Summary** and **Changelog**.
  - Use the "+ Auto-generate release notes" button to add details from included PRs.
  - Until we reach a `1.0.0` release check the "Pre-release" box.
- [x] Make sure the new release shows up on [crates.io] and that the docs are built correctly on [docs.rs].
- [x] Announce the release, using the **Summary**, on Discord, Twitter and Nostr.
- [x] Celebrate 🎉

[Semantic Versioning]: https://semver.org/
[crates.io]: https://crates.io/crates/bdk
[docs.rs]: https://docs.rs/bdk/latest/bdk
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

fixes #1435 

bdk_chain to 0.14.0
bdk_bitcoind_rpc to 0.10.0
bdk_electrum to 0.13.0
bdk_esplora to 0.13.0
bdk_file_store to 0.11.0
bdk_testenv to 0.4.0
bdk_persist to 0.2.0

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by evanlinjin** [comment]
Can we get #1403 in this release as well? Thanks!

**Comment by notmandatory** [comment]
> Can we get #1403 in this release as well? Thanks!

Sure! I'd love to get this one in too, is it ready to review?

**Comment by evanlinjin** [comment]
> > Can we get #1403 in this release as well? Thanks!
> 
> Sure! I'd love to get this one in too, is it ready to review? 

Yes it is!

**Review by ValuedMammal — APPROVED** [review]
ACK db9fdccc18c418cbbdf39ef4e912416796d63860

**Review by storopoli — APPROVED** [review]
ACK db9fdccc18c418cbbdf39ef4e912416796d63860

**Pull request merged**
