### PR TITLE
Use pass by reference for TxId when getting a transaction

### PR DESCRIPTION
**Pull request by benthecarman**
### Description

Small API cleanup I found

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by evanlinjin** [comment]
@benthecarman Thank you for the PR, what is the intention for this change?

**Comment by benthecarman** [comment]
> what is the intention for this change?

AFIAK this should be a small performance improvement as before a whole `TxId` was being passed around so it had to use its implementation of `Copy` instead of just using the reference.

**Comment by evanlinjin** [comment]
> > what is the intention for this change?
> 
> AFIAK this should be a small performance improvement as before a whole `TxId` was being passed around so it had to use its implementation of `Copy` instead of just using the reference.

What measure do we have to prove we have a "small performance improvement" from passing by value vs by reference?

**Comment by benthecarman** [comment]
Hmm that was my gut intuition but after doing some reading online seems to be a more nuanced debate. Benchmarking this would probably be a decent amount of effort for not much payoff.

Feel free to close if you'd like, was at least a learning experience for me haha

**Comment by LLFourn** [comment]
Yeah I think the best practice is to always pass `Copy` things by value and let LLVM figure out the rest.

**Pull request closed without merging**
