### PR TITLE
Add RPC Wallet Example

### PR DESCRIPTION
**Pull request by vladimirfomene**
### Description

This is a demonstration of how to create a wallet with a RPC syncing mechanism. This builds on #1041.

### Notes to the reviewers

Will love to hear your feedback on this current implementation. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [ ] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by nondiremanuel** [comment]
Better if it goes in alpha.2 together with #1041, but in case we can move it to alpha.3

**Comment by notmandatory** [comment]
I'm moving this to alpha.3 since #1041 already has a non-wallet example and this one will be easier to do once that's merged.

**Comment by notmandatory** [comment]
@vladimirfomene if you this it's still relevant, go ahead and copy/paste in the README from #1019 after you rebase this PR.

**Comment by evanlinjin** [comment]
Replaced by #1172

**Comment by notmandatory** [comment]
Moved this to beta release so we can focus final alpha releases on functional changes, leaving additional test/example/doc changes to beta milestone.

**Comment by notmandatory** [comment]
Closing since it's replaced by #1172

**Pull request closed without merging**
