### PR TITLE
chore: fix MSRV for flate2

### PR DESCRIPTION
**Pull request by evanlinjin**

### CODE REVIEW

**Comment by evanlinjin** [comment]
It's still broken, will revisit later (unless if someone would like to take over).

**Comment by realeinherjar** [comment]
I think that `rustls:0.21.7` needs to be changed to `rustls:0.21.8`

**Comment by notmandatory** [comment]
This is ready to re-review and merge. I don't want to have a broken CI holding up merging other PRs while we wait to figure out if it's OK to bump our MSRV with #1183.

**Comment by notmandatory** [comment]
I had to downgrade `hashbrown` since I can't even do a `cargo update` otherwise. It looks like the 0.10 and 0.11 versions are pointing to yanked versions of `ahash`.

**Review by notmandatory — APPROVED** [review]
ACK 95250fc44ed1372e77995d04ac2b380e0cb126a0

**Review by realeinherjar — APPROVED** [review]
ACK 95250fc44ed1372e77995d04ac2b380e0cb126a0

**Review by evanlinjin — COMMENTED** [review]
ACK 95250fc44ed1372e77995d04ac2b380e0cb126a0

**Pull request merged**
