### PR TITLE
docs: update CONTRIBUTING.md

### LINKED ISSUE #1394: Have more code conventions and guidelines
Using rustfmt means we always agree on code formatting. If rustfmt allows it, then matters of code style can be left to personal preference.

However we could benefit from defining more code conventions in `CONTRIBUTING.md` for the sake of consistency. Just some ideas:

- Forbid `unsafe` (or handle case by case)
- Use [StdExternalCrate](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#group_imports) style for grouping imports
- Return as much context as possible with errors
- Refer liberally to bitcoin BIPs and relevant historical context for a piece of code
- Follow rust API guidelines for [documentation](https://rust-lang.github.io/api-guidelines/documentation.html) and [naming](https://rust-lang.github.io/api-guidelines/naming.html)
- Name tests after the functional unit they're testing
- If using emoji, use them to their intended effect: [code-review-emoji-guide](https://github.com/erikthedeveloper/code-review-emoji-guide)

Approving changes:
- All comments resolved
- 2-ACK rule to merge

**Use case**  
Facilitates code review and improves readability of the codebase

**Additional context**
bitcoindevkit/bdk#1221 
https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1510453405

### PR DESCRIPTION
**Pull request by ValuedMammal**
Update `CONTRIBUTING.md` 

* Made small corrections and added some things that were missing. If there's something else you think should be included let me know.

closes #1394

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK 6b881f8ab46bd0f3c612e522df21dc48ae5e6955

**Comment by LagginTimes** [comment]
ACK 6b881f8ab46bd0f3c612e522df21dc48ae5e6955

**Review by storopoli — APPROVED** [review]
ACK 6b881f8ab46bd0f3c612e522df21dc48ae5e6955

**Review by oleonardolima — APPROVED** [review]
ACK 6b881f8ab46bd0f3c612e522df21dc48ae5e6955

**Pull request merged**
