### PR TITLE
Backporting "Fix policy condition calculation" onto release/0.28

### LINKED ISSUE #942: Merge or backport "Fix policy condition calculation"
**Describe the bug**  

See fix #932, it should be merged or backported to the `release/0.28` branch. This issue is a reminder that it needs to be done.

### PR DESCRIPTION
**Pull request by junderw**
Fixes #942

### Description

This backports "Fix policy condition calculation" (#932) onto release/0.28

### Notes to the reviewers

Currently kept the Author the same and the committer is myself. Let me know if this is not the desired outcome of the history. (I have made no modifications myself)

### Changelog notice

Backported "Fix policy condition calculation"

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by junderw** [comment]
Also, please let me know if I should point it at a different branch.

**Comment by notmandatory** [comment]
Thanks for doing this backport, commit history is fine. Seems to be some tests failing though, I can help take a look if you like.

**Comment by junderw** [comment]
I found the issue. Everything should build now.

**Review by notmandatory — APPROVED** [review]
ACK 9cffaad71f3d090196a3e35e84ad714118ea2846

Test fix looks good.

**Pull request merged**
