### PR TITLE
Make Esplora feature optional for CLI/REPL

### PR DESCRIPTION
**Pull request by eupn**
I found this low-hanging fruit [in Discord](https://discord.com/channels/753336465005608961/753336465005608964/785575944688500806) about making `esplora` optional for CLI.

### CODE REVIEW

**Comment by afilini** [comment]
Concept ACK, though I would return an error if an esplora server is specified while the feature is disabled. Something that tells the user to enable the feature first

**Comment by eupn** [comment]
It shouldn’t be possible to specify Esplora settings if the feature is not enabled. Clap/StructOpt will return an error that it doesn’t know about this parameter since it was excluded from the code.

**Comment by notmandatory** [comment]
ACK 5b34f0d
@eupn are you able to sign your commits? 

I tested `repl` with and without the `esplora` features. I can confirm that if the `esplora` feature is not used then esplora options return an appropriate error, ie:
```
$ cargo run --features cli-utils --example repl -- --descriptor "wpkh(tpubEBr4i6yk5nf5DAaJpsi9N2pPYBeJ7fZ5Z9rmN4977iYLCGco1VyjB9tvvuvYtfZzjD5A8igzgw3HeWeeKFmanHYqksqZXYXGsw5zjnj7KM9/*)" --esplora_concurrency 2 sync

error: Found argument '--esplora_concurrency' which wasn't expected, or isn't valid in this context
```

**Comment by eupn** [comment]
@notmandatory, let me set up signing tools. I'll force-push signed commits.

**Comment by eupn** [comment]
@notmandatory commits are signed.

**Comment by afilini** [comment]
I think you've only signed the last two commits, not all three. Sorry to bother you again with this.. :(

**Comment by eupn** [comment]
@afilini no worries, my bad!

**Comment by afilini** [comment]
ACK c9a05c0deb839b8c9c8f5dbd01e8694cdb9939fe, thanks!

**Pull request merged**
