### PR TITLE
Update `rusqlite` to `0.28.0`

### PR DESCRIPTION
**Pull request by w0xlt**
This PR updates `rusqlite` to `0.28.0`.

### CODE REVIEW

**Comment by notmandatory** [comment]
Please rebase to fix the CI error, we had a problem with one of the test dependency versions but should be OK now.

**Comment by w0xlt** [comment]
Rebased.

**Comment by w0xlt** [comment]
Closing this due to https://github.com/bitcoindevkit/bdk/pull/867

**Comment by notmandatory** [comment]
Oh shoot! sorry I forgot you had this PR pending or I would have used it. Thanks for closing.

**Pull request closed without merging**
