### PR TITLE
[ci] Build and publish nightly docs

### PR DESCRIPTION
**Pull request by afilini**
This workflow builds the doc for every commit merged on master and publishes it on `bitcoindevkit.org`. It kinda depends on bitcoindevkit/bitcoindevkit.org#15 so that as soon as a commit on `master` is made, that also gets published on GH pages

### CODE REVIEW

**Comment by afilini** [comment]
This is an example of what those automatic commits look like: https://github.com/afilini/bitcoindevkit.org/commit/a8b6ec78255fe85053ab9b7888e176c04755b3cb

**Comment by afilini** [comment]
Changed this to only keep the latest version instead of keeping a copy for every commit

**Comment by notmandatory** [comment]
utACK `4aac833`, looks good, this will be a great to have as we're adding new docs

**Comment by RCasatta** [comment]
utACK 4aac833

**Pull request merged**
