### PR TITLE
Release 0.20.0

### PR DESCRIPTION
**Pull request by notmandatory**
Proposed tweet:

📢 Release 0.20.0 is out! Highlights include bug fixes for the ElectrumBlockchain and descriptor templates, discourage fee sniping in tx building, and new tx signing options. A big thanks to our past and latest new contributors. For all changes see: https://github.com/bitcoindevkit/bdk/releases/tag/v0.20.0

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
We might want to do a thread on twitter, under the announcement tweet, to expand on the new features:

----------------------------
First, we automagically set the transaction nlocktime to prevent fee sniping.
How do we know the current blockchain height, you ask? We spy on you.

But you can also tell us, if you prefer.
Snap(4)

----------------------------
Then, some options for controlling the signer behavior. By default, we try to finalize the PSBT we sign, and, if we succeed, we strip the signatures - making your PSBT lighter 🪶
Snap(7)

----------------------------
Lastly, a method to get a certain block's hash. We use Blockstream's electrum endpoint here, but, as always, you can use the backend you prefer - your own RPC node, your uncle's electrum server, or some rando's esplora's endpoint.

We don't judge.

Snap(5)
----------------------------

The only thing is, we might want to change the announcement tweet a bit to signal that it's a thread. Something like "Highlights include bug fixes for the ElectrumBlockchain and descriptor templates, as long as some new features. Let's explore them 🧵👇 " maybe? What do you think?

**Comment by evanlinjin** [comment]
I like how new features are shown with pictures. Because bug-fixes are boring, we can just add it to the end of the thread in a single tweet imo

**Comment by notmandatory** [comment]
Love the code examples and commentary, tweets posted!

https://twitter.com/bitcoindevkit/status/1547349805675921408

**Comment by notmandatory** [comment]
Need someone to approve this PR so I can merge release branch back to `master` 🙏 !

**Review by danielabrozzoni — APPROVED** [review]

**Review by afilini — APPROVED** [review]
ACK 46c344feb02e2ecfdc065d85cba320d06811bedf

**Pull request merged**
