### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Add bug reporting issue template and template for proposing a "Summer of Bitcoin" project.

### Notes to the reviewers

The SoB template is basically a copy of what Adi created but lightly formatted to work as github issue templates.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by notmandatory** [comment]
@rajarshimaitra template here.

**Comment by rajarshimaitra** [comment]
@notmandatory thanks.. And where should the project proposal docs be placed?

**Comment by notmandatory** [comment]
I think once we agree on the SoB proposal issues we can send Adi the links, or if he needs them in google doc format we can copy/paste into google docs to send him.

**Comment by rajarshimaitra** [comment]
Got it.

**Review by afilini — APPROVED** [review]

**Pull request merged**
