### PR TITLE
Bump CI to Rust 1.51.0

### PR DESCRIPTION
**Pull request by RCasatta**
### Description

Increments CI rust stable version to released 1.51.0

### Notes to the reviewers

A new clippy warning is present with this rust version https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms dictated most of the changes

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] This pull request breaks the existing API

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK 733a9aa

Good to keep up with latest stable rust and clippy changes.

**Comment by notmandatory** [comment]
BTW, before this is merged we'll need to change the Github required checks for the `master` branch from `1.50.0` to `1.51.0`

**Review by notmandatory — CHANGES_REQUESTED** [review]
Now that #314 and #319 are merged it looks like this needs a re-base and a few new fixes before merging. Then this one should go in before anything else. Thanks!

**Comment by RCasatta** [comment]
@notmandatory rebased

**Review by notmandatory — APPROVED** [review]
ACK 1929654 Thanks!

**Pull request merged**
