### PR TITLE
refactor(hwi,wallet): enhance hardware wallet integration and testing

### PR DESCRIPTION
**Pull request by pluveto**
## Overview

This PR introduces enhancements to the hardware wallet integration within the `hwi` crate and improves the testing utilities in the `wallet` crate.

## Changes

1. Enabling `test-util` Feature
  The `bdk_wallet` dependency in the `hwi` crate now includes the `test-util` feature, allowing the use of additional testing utilities provided by the `bdk_wallet` crate.
2. refining `TransactionSigner` implementation
3. Re-enabling and updating hardware wallet signer test
  The previously disabled hardware wallet signer test has been re-enabled and updated to use the `test-util` feature. This includes improvements to the test structure and error handling, ensuring robust and comprehensive testing.
4. Move common test functions as `test-util` inside `wallet` crate
  A new `test-util` module has been added to the `wallet` crate to organize and provide utilities for testing. This promotes code reuse and maintainability across different tests.

### CODE REVIEW

**Comment by evanlinjin** [comment]
Thanks for this PR. I haven't had the opportunity to review this properly yet, however I am wondering if there is a particular reason why `bdk_wallet` is not a dev-dependency?

**Comment by evanlinjin** [comment]
Also, can you please remove the merge commit and do a rebase instead? Thank you

**Comment by pluveto** [comment]
OK.

`insert_tx` has been refactor in 324eeb3eb4e5231c6a81e6d197df788ad08b23a8. I need to reorganize the code.

**Comment by pluveto** [comment]
Reorganized and moved `bdk_wallet` with `test-util` feature flag into `dev-dependency`.

Ready for review. Please take a look.

**Comment by pluveto** [comment]
It seems that the HWI emulator is [disabled](https://github.com/bitcoindevkit/bdk/blob/master/.github/workflows/code_coverage.yml#L30), which caused the HWI-related tests to fail.

Therefore, I have added it ([add HWI emulator setup](https://github.com/bitcoindevkit/bdk/pull/1492/commits/6141841a195c847f0a9f6dfccc36aec0a9a62a35)).

**Comment by pluveto** [comment]
CI issue is [fixed](https://github.com/pluveto/bdk/actions/runs/9916521045/job/27398886874) by specific OpenSSL config. https://github.com/bitcoindevkit/bdk/pull/1492/commits/15d6d9a9050844c0709e998dd042dbfbf04068aa

**Comment by ValuedMammal** [comment]
I appreciate what is accomplished in this PR. I'm somewhat ambivalent toward having this change. Main concern is bringing python dependency back to CI considering the age of this emulator software and that the nano s hasn't seen a firmware update since 2021 which amounts to more of a maintenance burden than I think is warranted. Other folks might have different opinions. In any case if you decide to continue work on this branch, we'd like if you also signed commits, although for the record I realized that policy isn't well documented.

**Comment by pluveto** [comment]
Thank you for your feedback. I've updated the emulator model used for the firmware to a more recent version. Additionally, I've resubmitted the commits with signatures. Thanks!

**Comment by oleonardolima** [comment]
Thanks for working on this! However, after #1561 the `HWISigner` and therefore the `TransactionSigner` implementation has moved to [`rust-hwi`](https://github.com/bitcoindevkit/rust-hwi), so I guess we could close this PR (cc @notmandatory).

Feel free to open a PR in `rust-hwi` with your suggested enhancements, I also think we could reuse the approach of having a test util, exposing it through `bdk_testenv`, and use it there at `rust-hwi` for testing.

**Pull request closed without merging**
