### PR TITLE
types: Make Utxo::Foreign::sequence not optional

### PR DESCRIPTION
**Pull request by stevenroose**
It's never kept internally as optional at this point.

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK 2a7ddfbc6f1885b0229bf14d3128ed79659d32e3

**Review by oleonardolima — APPROVED** [review]
utACK 2a7ddfbc6f1885b0229bf14d3128ed79659d32e3

**Comment by notmandatory** [comment]
I signed the commit so this can be merged.

**Review by notmandatory — APPROVED** [review]
ReACK d96dac426187379890fb84315a51d81f37bbd0dc

**Pull request merged**
