### PR TITLE
ci (maintenance): Pin byteorder, webpki to keep the MSRV

### PR DESCRIPTION
**Pull request by danielabrozzoni**

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK c37b5874f3776aa73b604852f4362d23c6b08420

**Comment by notmandatory** [comment]
Having the same issue with download `bitcoind` that the `master` branch is having, see bitcoindevkit/bdk_wallet#129.

**Comment by danielabrozzoni** [comment]
Ops, I by accident included a WIP commit, which I just squashed. @notmandatory can you ACK again?

I'm re-running the CI jobs until bitcoind behaves and tests are passing 🤷🏻‍♀️

**Review by evanlinjin — APPROVED** [review]
ACK 67b083fa03f116effe787fd7c1ba17c739d963ce

**Pull request merged**
