### PR TITLE
Test electrum ext

### PR DESCRIPTION
**Pull request by vladimirfomene**
### Description

This PR tests our Electrum scanning logic

### Notes to the reviewers

I will leave this in draft for now because the test still occasionally fail. I'm still trying to figure out why but the root cause of the bug is hard to find because the bug occurs occasionally.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by evanlinjin** [comment]
@vladimirfomene This doesn't seem to build for `1.57.0`. Could you figure out a way, to have the CI skip these tests for `1.57.0`?

Also, could you provide more details for the failing tests? Thank you.

**Comment by vladimirfomene** [comment]
@evanlinjin, was able to get the test to compile with 1.57. Here are the two errors I occasionally get. 
two-test-failed

**Comment by LLFourn** [comment]
We have a bug in #1145 that having tests like this PR introduced may have caught. I think we want to introduce a test in that PR to reproduce the issue. If this PR already reproduces the issue then we could use this one. In any case the groundwork here should be useful. I think this PR can be improved by not using concepts like `miniscript` or `KeychainTxOutIndex` since we are only trying to test the electrum logic (not `bdk_chain`). it's easy enough to call the APIs here by just putting some spks in a `Vec` or whatever. In the case of #1145's bug we just need to check the chain returned is correct.  

@vladimirfomene wdyt?

**Comment by notmandatory** [comment]
Test coverage is good for electrum client see #906. We can add more testing for new scenarios as needed. Closing this PR as it's out of date.

**Pull request closed without merging**
