### PR TITLE
Derive `PartialEq`, `Eq` on `SyncTime`

### PR DESCRIPTION
**Pull request by MaxFangX**
### Description

This enables e.g. `assert_eq!` comparisons of `SyncTime` in tests (we use this)

### Changelog notice

Derived `PartialEq`, `Eq` on `SyncTime`

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
Looks good, we just changed our CI MSRV so you'll need to do a rebase to pick that up.

**Comment by MaxFangX** [comment]
@notmandatory rebased, awaiting approval again for running CI

**Review by rajarshimaitra — APPROVED** [review]
ACK 45d41416ede5d2e26a8ef4c2cac6f44d0346fb23

**Review by evanlinjin — APPROVED** [review]
ACK 45d41416ede5d2e26a8ef4c2cac6f44d0346fb23

No-brainer.

**Pull request merged**
