### PR TITLE
Create rust.yml

### PR DESCRIPTION
**Pull request by BizXcentral**
#### All Submissions:

* [ ] I've signed all my commits
* [ ] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Review by storopoli — CHANGES_REQUESTED** [review]
NACK.
How is this different from https://github.com/bitcoindevkit/bdk/blob/master/.github/workflows/cont_integration.yml ?
Just the `-- verbose` flag?

**Review by BizXcentral — COMMENTED** [review]
Minimal changes

**Comment by storopoli** [comment]
How adding a WHOLE NEW CI FILE with no new functionality since it is already covered in previous CI files a "minimal changes"?

Sorry, but please take a look at https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md and adjust your PR accordingly?

There are several of "minimal changes" that I can add to any bitcoin opensource codebase that would be catastrophic...

**Comment by evanlinjin** [comment]
I'm confused what the purpose of this is. The fact that there is no PR description does not help either. Closing.

**Pull request closed without merging**
