### PR TITLE
fix: more typos

### PR DESCRIPTION
**Pull request by realeinherjar**
More typos fix before #1165

### Changelog notice

Fix more typos in the docs

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by notmandatory** [comment]
I moved this to the beta milestone so we can collect more typo fixes if they come up here.

**Comment by realeinherjar** [comment]
This is ready to merge and it is a block for #1165

**Comment by ValuedMammal** [comment]
looks like in #1220  this got corrected to 'should' instead of 'could'

https://github.com/bitcoindevkit/bdk/blob/46d39beb2caa759f19bcf3e6397de3029b1aab6a/crates/bdk/src/wallet/signer.rs#L761-L762

**Comment by ValuedMammal** [comment]
https://github.com/bitcoindevkit/bdk/blob/46d39beb2caa759f19bcf3e6397de3029b1aab6a/crates/bdk/src/wallet/coin_selection.rs#L189-L190

deducing -> deducting

**Comment by ValuedMammal** [comment]
after #1178 the doc for ‎`Store::aggregate_changesets` is stale.

https://github.com/bitcoindevkit/bdk/blob/46d39beb2caa759f19bcf3e6397de3029b1aab6a/crates/file_store/src/store.rs#L138-L142

it could say something like
```
/// This function returns the aggregate changeset, which may be `None` if nothing 
/// was persisted. If reading or deserializing any of the entries fails, an error is 
/// returned that includes all those it was able to read.
```

**Comment by storopoli** [comment]
We can close this

**Pull request closed without merging**
