### PR TITLE
[rpc] rescan in chunks of 10_000 blocks

### PR DESCRIPTION
**Pull request by RCasatta**
### Description

Importing a descriptor on RPC starts a unique rescan of the blockchain, this splits the rescan call to operate on 10_000 blocks each at maximum, while updating the log_progress, providing the user more feedback.

In case the rescan process is interrupted, it would start from the latest finished chunk instead of from the beginning

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Review by tcharding — COMMENTED** [review]
For what its worth, LGTM. I was successfully able to run the tests `cargo test --features test-rpc` on this branch.

**Review by tcharding — APPROVED** [review]

**Comment by rajarshimaitra** [comment]
Concept ACK.. 

Will review deeper..

**Comment by notmandatory** [comment]
Needs a rebase to pickup latest esplora Blockchain test and CI changes

**Comment by rajarshimaitra** [comment]
tACK https://github.com/RCasatta/bdk/commit/eb068720820c9611731c6fe05f7b7f1111c67c9f

Code changes looks good to me. 
Created 20K blocks in regtest. verified the setup loops through rescan twice..

**Review by notmandatory — APPROVED** [review]
utACK c23692824d0aa49ada61a79c0da13070fda3fcec

**Pull request merged**
