### PR TITLE
Correction of the coin type in the testnet wallet example descriptors 

### PR DESCRIPTION
**Pull request by casey-bowman**
### Description

Corrects the derivation path for the three wallet examples. For testnet, the coin type should be 1 instead of 0.

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
This looks good to me, thanks! Can you please squash your commits in a single one (or drop the first 5 commits altogether), and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for the commit message?

**Comment by notmandatory** [comment]
We're not using the `release/1.0.0-alpha` branch so this PR needs to be merged to the `master` branch and you'll need to rebase on top of the `master` branch to pickup the latest commits.

**Comment by casey-bowman** [comment]
> This looks good to me, thanks! Can you please squash your commits in a single one (or drop the first 5 commits altogether), and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for the commit message?

I'll work on getting this squashed and rebased on master, after some other work I need to do, and switch to using the conventional commits spec, too. 

Thanks for all your work on BDK! It's been great working with it so far.

**Comment by casey-bowman** [comment]
Closed, superseded by PR #1089

**Pull request closed without merging**
