### PR TITLE
Use cargo 1.62.0 in CI

### PR DESCRIPTION
**Pull request by danielabrozzoni**
#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
Can this wait until the `0.21` release? or should we try to get it into the `0.20` we're code freezing today?

**Comment by notmandatory** [comment]
Looks like still some `clippy` errors to fix and then this one is ready to merge and cherry-pick to `release/0.20.0` branch.

**Comment by danielabrozzoni** [comment]
> Looks like still some clippy errors to fix and then this one is ready to merge and cherry-pick to release/0.20.0 branch.

Yeah, I'm trying to see how to fix them, I hope it won't take too long, otherwise we'll just release this in 0.21 🤷🏻‍♀️

**Comment by danielabrozzoni** [comment]
Speaking with @afilini, we decided that this one can wait - the fix to the cargo clippy annotation is not really trivial, and `bdk_core` would solve this soon anyways. Closing.

**Pull request closed without merging**
