### PR TITLE
Release/0.13.0

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Merge the 0.13.0 bdk release into the master branch.

### Notes to the reviewers

Additional changes made in release branch:
* Cherry picked commits from #454
* Update dev-dependencies electrsd to 0.12 ee8b992f8bb9f648b0593b9eead877ec1906d154
* Switch back to rust-bitcoin/rust-bitcoincore-rpc 87815997403c3a4652f2ad295d44919f12e45241

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
`cargo-audit` found two issue we'll need to fix before `0.13.0` is ready.

Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree: 
time 0.1.43
└── zip 0.5.13
    └── electrsd 0.10.0
        └── bdk 0.13.0-rc.1

Crate:         failure
Version:       0.1.8
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree: 
failure 0.1.8
└── tiny-bip39 0.7.3
    └── bdk 0.13.0-rc.1

error: 1 vulnerability found!
warning: 1 allowed warning found

**Comment by notmandatory** [comment]
I've created a PR to update the `zip` crate to use the latest version of `time`, hopefully this gets merged and released soon, and then we'll also need a new version of `electrsd` from @RCasatta . 
https://github.com/zip-rs/zip/pull/254

**Comment by notmandatory** [comment]
Instead of requiring a change to the `zip` crate I created an `electrsd` PR that should fix this issue, see https://github.com/RCasatta/electrsd/pull/23.

**Comment by RCasatta** [comment]
electrsd with RCasatta/electrsd#23 merged and released as 0.12.0 (also with electrs 0.9.1)

**Comment by notmandatory** [comment]
Added commits to switch to electrs 0.12 and to switch the rest of BDK back to rust-bitcoin/rust-bitcoincore-rpc.

**Review by afilini — APPROVED** [review]

**Comment by afilini** [comment]
There are conflicts on `Cargo.toml`, I don't know which one of the two libraries is the right one: `core-rpc` i believe is published by @RCasatta, do we still need to use it or we can switch back to `bitcoincore-rpc`?

**Comment by RCasatta** [comment]
I confirm we need to switch back to rust-bitcoincore-rpc now that they have upgraded rust-bitcoin and released

**Pull request merged**
