### PR TITLE
feat(chain,core)!: move `Merge` to `bdk_core`

### LINKED ISSUE #1624: Move `Merge` trait to `bdk_core`.
**Describe the enhancement**  

The title says it all.

**Use case**  

This way, append-based persist crates (such as `bdk_file_store`) will only need to depend on `bdk_core`.

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #1624

### Description

Moving `Merge` into `bdk_core` (from `bdk_chain`) allows persist crates to only depend on `bdk_core`.

### Changelog notice

* Move `Merge` into `bdk_core`.
* Remove `bdk_chain` dependency from `bdk_file_store`.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Review by oleonardolima — APPROVED** [review]
ACK a4cf905d75ad7e09730b6d0aab5ef6cd2e735c2b

I tested it with the examples, and they worked fine. It's valid to notice that they still use it from `bdk_chain`, as it's reexporting it from `bdk_core`.

**Review by ValuedMammal — APPROVED** [review]
ACK a4cf905d75ad7e09730b6d0aab5ef6cd2e735c2b

**Comment by LagginTimes** [comment]
ACK a4cf905d75ad7e09730b6d0aab5ef6cd2e735c2b

**Review by notmandatory — APPROVED** [review]
ACK a4cf905d75ad7e09730b6d0aab5ef6cd2e735c2b

**Pull request merged**
