### PR TITLE
Bump CI Rust stable version to 1.65.0 

### PR DESCRIPTION
**Pull request by yukibtc**
### Description

* Fix clippy for Rust 1.65.0  
* Bump CI Rust stable version to 1.65.0

#### All Submissions:

* [X] I've signed all my commits
* [X] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [X] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by yukibtc** [comment]
Seems that the CI fails for electrsd

**Comment by notmandatory** [comment]
Thanks, this looks about ready to go. I'm going to target it for early in the 0.27 release so fewer nearly done PRs need to be rebased.

**Review by rajarshimaitra — APPROVED** [review]
tACK 353d0c11045b7858a70aeb95464e184d8c90c785

Changes looks good to go..

**Comment by rajarshimaitra** [comment]
ReACK fb76c9ed9a0764a1e82d5c12a5e8104e26ef0ee5

**Review by rajarshimaitra — APPROVED** [review]
ReACK fb76c9ed9a0764a1e82d5c12a5e8104e26ef0ee5

**Pull request merged**
