### PR TITLE
Turn on rustfmt merge_imports

### PR DESCRIPTION
**Pull request by LLFourn**
Was brought up here: https://github.com/bitcoindevkit/bdk/pull/279#r572591694

So I made  PR to see what it would look like and to see if we have overwhelming support for it. I think I prefer merge imports as it's easier to see what top level modules are being imported. It does add some more LoC funnily enough.

Voice your opinion. There are also other options we could turn on in rustfmt. See [here](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=) which could be added to the PR.

### CODE REVIEW

**Comment by notmandatory** [comment]
I prefer the out of the box imports style since it's what most other projects use, unless there's a compelling reason to change it. That said, the merged imports are easy enough to read and `rustfmt` does all the work, so if others are strongly for it I'm not strongly against.

**Comment by RCasatta** [comment]
Personally, I slightly prefer without nested imports

**Comment by tcharding** [comment]
I prefer non-merged imports. There are trade offs, the main ones being IMO

pro of merge imports:
- Easier tooling support
- Less cluttered

cons of merged imports
- diffs are bigger
- use statement changes in the diff often cause merge conflicts

Personally I think the merge conflict thing is the biggest consideration hence my preference for non-merged imports.

Sorry @LLFourn if my comment on the PR that you link to was misleading, I already had an opinion but did not air it then.

**Comment by afilini** [comment]
I can't really describe why (maybe it's just that I'm more used to them), but I also like the current non-merged style better..

**Comment by LLFourn** [comment]
Thanks all.

**Pull request closed without merging**
