### PR TITLE
Fix sent calculation in the RPC backend 

### PR DESCRIPTION
**Pull request by danielabrozzoni**
#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] I've added tests to reproduce the issue which are now passing

### CODE REVIEW

**Comment by afilini** [comment]
Needs rebasing to fix the CI and then we can merge this

**Comment by danielabrozzoni** [comment]
Done :)

**Comment by afilini** [comment]
ACK bfd0d13779003f11fa099a0b665052c18ce6e500

**Review by afilini — APPROVED** [review]
ACK bfd0d13779003f11fa099a0b665052c18ce6e500

**Pull request merged**
