### PR TITLE
fix!(chain): Make spk revelation return owned spks

### PR DESCRIPTION
**Pull request by LLFourn**
Unfortunately there's no way to return a lifetime to something from a `&mut self` that doesn't extend the lifetime of the mutable borrow. So it's better not borrow at all here.

I think @evanlinjin tried to make this change some time ago but I NACK'd it. Now I understand why it's unavoidable.  Sorry!

### CODE REVIEW

**Comment by notmandatory** [comment]
This needs a rebase but otherwise looks good to me.

**Review by oleonardolima — COMMENTED** [review]
Concept ACK

**Comment by notmandatory** [comment]
@LLFourn  is it OK if someone else takes this over and rebases it?

**Comment by ValuedMammal** [comment]
I think it can be done in #1438

**Comment by notmandatory** [comment]
Closing this PR as equivalent fixes are included in #1451.  a5142decfcd0581bf871755b8130782666329017

**Pull request closed without merging**
