### PR TITLE
Applying blocks API

### LINKED ISSUE #903: Applying blocks APIs
We need a set of APIs to easily apply blocks to a keychain tracker. I propse the following:

* `ChainGraph::<ConfirmationTime>::from_block(block)`: This creates a chain graph with two checkpoints (one for the block at height and one for prev block hash).
* `KeychainTracker::apply_update_relevant(scan: KeychainScan)`, does this same thing as `apply_update` but doesn't not take transactions that don't send to or from things in the txout index. Also add `determine_relevant_changeset`.
* `ChainGraph::apply_update_relevant(|tx| is_this_relevant(tx))` same as above except you can pass a predicate (also needs the changeset option).

~In addition to adding these APIs it looks like `KeychainTracker::determine_changeset` has a TODO in it that needs to be fixed before this whole workflow will work properly:~

Old ticket: https://github.com/LLFourn/bdk_core_staging/issues/193

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Closes #903 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

### CODE REVIEW

**Comment by notmandatory** [comment]
@danielabrozzoni does this PR need to be rebase/worked now that that #976 is merge?

**Comment by danielabrozzoni** [comment]
I'm really not sure, @evanlinjin is this PR still needed?

**Comment by evanlinjin** [comment]
> I'm really not sure, @evanlinjin is this PR still needed?

It definitely needs further discussion. It depends if everyone is happy with my approach in #1041, or do we feel that having an `apply_blocks` method is strictly better?

**Comment by LLFourn** [comment]
> > I'm really not sure, @evanlinjin is this PR still needed?
> 
> It definitely needs further discussion. It depends if everyone is happy with my approach in #1041, or do we feel that having an `apply_blocks` method is strictly better?

I think having `apply_block` is a better approach after reviewing #1041.

**Comment by danielabrozzoni** [comment]
Closing as the approach changed radically anyways

**Pull request closed without merging**
