### PR TITLE
Fix clippy warnings for 'all-targets'

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

When @rajarshimaitra tried to use the `cargo-check.sh` script he found some clippy warnings were failing. I fixed it so that this script does not test against `+nightly` since our CI only tests on `1.46.0` and  +stable (currently `1.51.0`). I also enabled `clippy +all-targets` in our `build-test` CI job and fixed related clippy errors in the test code.  

### Notes to the reviewers

Overall this change tightens our `clippy` check to include all targets (ie. --lib --bins --tests --benches --examples). 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Review by RCasatta — COMMENTED** [review]
Are we sure we want to maintain a script `scripts/cargo-check.sh`  which is not launched by the CI? The risk is that we forgot to keep that in sync like it's happened...

we should probably launch it from the CI or remove it

**Comment by rajarshimaitra** [comment]
Yes, I think it's probably better to remove it if it's not being used in development. Having the script in the repo might give a false impression that it **should** work to newcomers.

**Comment by notmandatory** [comment]
Yes I agree it's better to remove the script rather than try to keep it in sync with CI.

**Comment by rajarshimaitra** [comment]
Tested ACK.

I am getting two warnings though.

```
warning: 2 warnings emitted

warning: manual implementation of `Option::map`
  --> src/psbt/mod.rs:30:20
   |
30 |               } else if let Some(in_tx) = &input.non_witness_utxo {
   |  ____________________^
31 | |                 Some(in_tx.output[tx.input[input_index].previous_output.vout as usize].clone())
32 | |             } else {
33 | |                 None
34 | |             }
   | |_____________^ help: try this: `input.non_witness_utxo.as_ref().map(|in_tx| in_tx.output[tx.input[input_index].previous_output.vout as usize].clone())`
   |
   = note: `#[warn(clippy::manual_map)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_map

warning: inconsistent struct constructor
   --> src/wallet/coin_selection.rs:256:9
    |
256 | /         OutputGroup {
257 | |             weighted_utxo,
258 | |             effective_value,
259 | |             fee,
260 | |         }
    | |_________^ help: try: `OutputGroup { weighted_utxo, fee, effective_value }`
    |
    = note: `#[warn(clippy::inconsistent_struct_constructor)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor
    ```

**Comment by notmandatory** [comment]
> Tested ACK.
> 
> I am getting two warnings though.
> 
> ```
> warning: 2 warnings emitted
> 
> warning: manual implementation of `Option::map`
>   --> src/psbt/mod.rs:30:20
> ...
> warning: inconsistent struct constructor
>    --> src/wallet/coin_selection.rs:256:9
> ...
> ```

Thanks for checking but these warnings are just for `+nightly`. I decided not to fix clippy warnings from `+nightly` since for this project we're only promising to support up to the `+stable`.  I'm not sure if `+nightly` warnings could change before they become stable.

**Review by afilini — APPROVED** [review]

**Pull request merged**
